services:
  - type: web
    name: farmer-rental
    env: python
    plan: free
    buildCommand: ""
    startCommand: python app.py
    envVars:
      - key: DB_HOST
        value: your-database-host
      - key: DB_USER
        value: your-database-user
      - key: DB_PASSWORD
        value: your-db-password
      - key: DB_NAME
        value: your-db-name
